config/routes.rb
Blog::Application.routes.draw do

  get "posts/index"

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :search_suggestions

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :posts
    end

    resources :posts 
  end

  scope "api" do
    resources :posts do
      resources :comments
      get 'page/:page', :action => :index, :on => :collection 
    end
    resources :users
  end

  resources :posts do
    resources :comments
  end

  root to: "main#index"

  match "posts/:id" => 'main#index'

  match 'index' => 'home#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title
  validates :title, :presence => true, :length => { :maximum => 70,
  	:too_long => "%{count} characters is the maximum allowed" }
  validates :content, :presence => true

  has_many :comments, dependent: :destroy

  def self.search(term)
  	where("content like :term or title like :term", term: "%#{term}%")
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController

  before_filter :find_post, :only => [:show, :edit, :update, :destroy]
  
  def index
    if params[:search]
      @posts = Post.search(params[:search]).page(params[:page]).per(10)
    else
  	  @posts = Post.order("id DESC").page(params[:page]).per(10)
    end
  end

  def show

  end

  def edit

  end

  def new
  	@post = Post.new
  end

  def create
    @post = Post.new(params[:post])
  	if @post.save
  		flash[:notice] = "Post has been created."
  		redirect_to admin_posts_path
  	else
  		flash.now[:alert] = "Post has not been created."
  		render :action => "new"
  	end
  end

  def update
  	if @post.update_attributes(params[:post])
  		flash[:notice] = "Post has been updated."
  		redirect_to admin_posts_path
  	else
  		flash[:alert] = "Post has not been updated."
  		render :action => "edit"
  	end
  end

  def destroy
	@post.destroy
	flash[:notice] = "Post has been deleted."

  	redirect_to admin_posts_path
  end

  private
  	def find_post
  		@post = Post.find(params[:id])
  	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	#respond_to :json

	def index
		#respond_with Post.all
		if params[:page]
   			@posts = Post.page(params[:page]).per(10)
   		else
			@posts = Post.all
		end

		respond_to  do |format|
			format.html
			format.json { render json: @posts }
		end
	end

	def show
		#respond_with Post.find(params[:id])
		@post = Post.find(params[:id])
		
		respond_to do |format|
			format.html
			format.json { render json: @post }
		end
	end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @user, @post] do |f| %>
	<% unless @post.errors.empty? %>
		<%= @post.errors.full_messages.each do |msg| %>
			<p> <%= msg %></p>
		<% end %>
	<% end %>

	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :content %>
		<%= f.text_area :content %>
	</p>

	<%= f.submit %>
<% end %>

app/views/admin/posts/_search.html.erb
<%= form_tag admin_posts_path, method: :get do %>
  <%= text_field_tag :search, params[:search], size: 30 %>
  <%= submit_tag "Search", name: nil %>
<% end %>

app/views/admin/posts/edit.html.erb
<h2>Editing a post</h2>
<%= render 'form' %>

app/views/admin/posts/index.html.erb
<div id="new_post">
	<%= link_to "New post", new_admin_post_path, :id => "new" %>
</div>

<div id="search_form">
	<%= render 'search' %>
<div>

<div class="paginator">
	<%= paginate @posts %>
</div>

<div id="posts">
	<% @posts.each do |post| %>
		<div class="post_title">
			<p><%= post.title %></p>
		</div>
		<div class="post_content">
			<p><%= truncate(post.content, :length => 100) %>
			</p>
			<%= link_to "Edit post",
				edit_admin_post_path(post), :id => "edit" %>
			<%= link_to "Remove post", admin_post_path(post), :id => "delete", :method => :delete %>
		</div>
	<% end %>
</div>

<div class="paginator">
	<%= paginate @posts %>
</div>

app/views/admin/posts/new.html.erb
<%= render 'form', :post => @post %>